sudo: required
dist: xenial
language: rust
cache: cargo
env:
rust:
- stable
- beta
- nightly

install:
- export CLANG_TAR=clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
- wget http://releases.llvm.org/7.0.1/$CLANG_TAR
- export CLANG_PATH=/opt/clang_llvm7
- sudo mkdir -p $CLANG_PATH
- sudo tar xf $CLANG_TAR -C $CLANG_PATH
- export PATH="$CLANG_PATH/bin:$PATH"
- echo $PATH
- clang --version
- llvm-config --version

matrix:
  fast_finish: true
  allow_failures:
  - env: NAME='nightly-publish'
  include:
  - rust: nightly
    sudo: required
    env: NAME='nightly-publish'
    before_script:
    - rustup component add rustfmt
    - rustup component add clippy
    - cargo install cargo-update || echo "cargo-update already installed"
    - cargo install cargo-travis || echo "cargo-travis already installed"
    - cargo install-update -a
    script:
    - cargo fmt -- --check
    - cargo clippy -- -D clippy
    - |
      cargo build    --verbose &&
      cargo coveralls --verbose
    - |
      cargo doc --verbose &&
      cargo doc-upload
    addons:
      apt:
        packages:
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - binutils-dev
        - cmake

script: |
  cargo build --verbose --release &&
  cargo test --verbose -- --test-threads 1 &&
  cargo bench --verbose &&
  cargo doc   --verbose

notifications:
  email: false
